apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: sample-catalog
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: gcr.io/rich-access-174020/ssuresh-operator-catalog:v1.0.2
  displayName: Sample
  publisher: sukhil-suresh
  updateStrategy:
    registryPoll:
      interval: 1h
