apiVersion: debug.ssuresh.io/v1
kind: Sample
metadata:
  name: sample
spec:
  hook:
    secret:
      enable: false
      namespace: sample
    role:
      enable: false
      namespace: openshift-config
